name: Backend Dev/Test - Deploy

## workflow will need manual trigger from actions page
on:
  workflow_dispatch:
        
env:
  GCP_PROJECT_ID: world-engine-test
  GCP_COMPUTE_INSTANCE_STAGING: dev-gamebackend-agar-shooter--1
  GCP_ZONE: us-west1-b
  GCP_SERVICE_DEPLOY_DIR: /opt/agar-shooter

jobs:
  backend-deploy-dev-test:
    runs-on: ubuntu-latest
    ## Add "id-token" with the intended google-github-actions/auth permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GCP auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: GCP - Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: GCP - SCP compose files
        run: |
          gcloud compute ssh --zone "${{ env.GCP_ZONE }}" "${{ env.GCP_COMPUTE_INSTANCE_STAGING }}"--project "${{ env.GCP_PROJECT_ID }}" --quiet -- "bash -c 'mkdir -p /tmp/agar-shooter'"
          gcloud compute scp --zone "${{ env.GCP_ZONE }}" --recurse * "${{ env.GCP_COMPUTE_INSTANCE_STAGING }}":/tmp/agar-shooter --project "${{ env.GCP_PROJECT_ID }}" --quiet
      - name: Set RELEASE_VERSION value (branch name)
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: GCP - Compute deploy exec
        id: compute-ssh-deploy
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: ${{ env.GCP_COMPUTE_INSTANCE_STAGING }}
          zone: ${{ env.GCP_ZONE }}
          ssh_private_key: ${{ secrets.DARK_FOREST_DEPLOY_RSA }}
          command: |
            sudo mkdir -p ${{ env.GCP_SERVICE_DEPLOY_DIR }}
            sudo rm -rf ${{ env.GCP_SERVICE_DEPLOY_DIR }}/*
            sudo chown runner:runner ${{ env.GCP_SERVICE_DEPLOY_DIR }}
            echo "Deploying: ${{ env.RELEASE_VERSION }}"
            mv /tmp/agar-shooter/* ${{ env.GCP_SERVICE_DEPLOY_DIR }}/
            cd ${{ env.GCP_SERVICE_DEPLOY_DIR }}
            git config --global --add url."git@github.com:".insteadOf "https://github.com/"
            bash ./start.sh build-only
      - name: GCP - Check Deployments
        id: compute-ssh-check-deployment
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: ${{ env.GCP_COMPUTE_INSTANCE_STAGING }}
          zone: ${{ env.GCP_ZONE }}
          ssh_private_key: ${{ secrets.DARK_FOREST_DEPLOY_RSA }}
          command: |
            cd ${{ env.GCP_SERVICE_DEPLOY_DIR }}
            docker compose ps | tr -d \'\"
            docker compose ps --status running | grep cardinal > /dev/null
            docker compose ps --status running | grep nakama > /dev/null
      - name: GCP - Deployment Output Dev/Test Instances
        run: |-
          echo "----------------------------------------------"
          echo "🎉 Agar Shooter backend deployed to dev/test instances: [${{ env.RELEASE_VERSION }} || 'latest' }}]"
          printf "${{ steps.compute-ssh-check-deployment.outputs.stdout }}"
          echo "----------------------------------------------"
